### ISSUE TITLE
Request to extend README

### ISSUE THREAD

**Issue by ar-mac** [galuszkak/k8s-presentation#1]
Hi @galuszkak 
Could you extend README showing the process of deploying this app? As for person totally unfamiliar with kubernetes, it's not obvious how to make this up and going, to try k8s by itself.
Commands, (screenshots would be awesome)
Maybe link to working app?

BTW Thanks for the very nice presentation 👏

**Comment by galuszkak** [comment]
@pokiujf I've added some small README (but at least it some start), and I've updated most of the repo, adding some new stuff. Let me know if this works for You and what is unclear/where You see there is need for clarification

**Comment by galuszkak** [comment]
@pokiujf closing.
